# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13365350caabed4a20e86ba8cde35abb6808b01f4cee6492dcc305b0c1aac1dc8972ffd136d6d1fdd3dde4bc899f85dd4f8ad511a7a830c39eefa7e4ab7cdcc4

test:
  secret_key_base: 0e013fccd11cbfd939aec45491067122f36f39c38db3dc9fdb7756a320937a8c9c0774bbd0579248230170715a45862e0d91cd906eccb570a48cd61e73ffb7d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
